"""Initial schema

Revision ID: 38ff49c933e7
Revises: 
Create Date: 2026-04-07 01:46:43.318475
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '38ff49c933e7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('notification_email_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('tracked_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('instagram_username', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('check_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tracked_account_id', sa.String(length=36), nullable=False),
    sa.Column('follower_count', sa.Integer(), nullable=False),
    sa.Column('following_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('success', 'partial', 'error', name='snapshot_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('snapshot_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tracked_account_id'], ['tracked_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('change_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tracked_account_id', sa.String(length=36), nullable=False),
    sa.Column('previous_snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('current_snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('change_type', sa.Enum('new_follower', 'lost_follower', 'new_following', 'lost_following', name='change_type'), nullable=False),
    sa.Column('instagram_username', sa.String(length=255), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['current_snapshot_id'], ['snapshots.id'], ),
    sa.ForeignKeyConstraint(['previous_snapshot_id'], ['snapshots.id'], ),
    sa.ForeignKeyConstraint(['tracked_account_id'], ['tracked_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshot_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('instagram_username', sa.String(length=255), nullable=False),
    sa.Column('relationship_type', sa.Enum('follower', 'following', name='relationship_type'), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snapshot_members_snapshot_id'), 'snapshot_members', ['snapshot_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('change_event_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['change_event_id'], ['change_events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_snapshot_members_snapshot_id'), table_name='snapshot_members')
    op.drop_table('snapshot_members')
    op.drop_table('change_events')
    op.drop_table('snapshots')
    op.drop_table('tracked_accounts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
